// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package queries

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users(username, password, created_at, updated_at) values(?, ?, ?, ?)

returning id, username, password, created_at, updated_at
`

type CreateUserParams struct {
	Username  string
	Password  string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
