// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_file.sql

package queries

import (
	"context"
)

const createFile = `-- name: CreateFile :one
insert into files(name, created_at, updated_at, user_id) values(?, ?, ?, ?)

returning id, name, created_at, updated_at, user_id
`

type CreateFileParams struct {
	Name      string
	CreatedAt string
	UpdatedAt string
	UserID    int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
