// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_file.sql

package queries

import (
	"context"
)

const getFile = `-- name: GetFile :one
select id, name, created_at, updated_at, user_id, deleted from files where name = ? and user_id = ?
`

type GetFileParams struct {
	Name   string
	UserID int64
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, arg.Name, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Deleted,
	)
	return i, err
}
