// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_user_by_username.sql

package queries

import (
	"context"
)

const getUserByUname = `-- name: GetUserByUname :one
select id, username, password, created_at, updated_at from users where username = ?
`

func (q *Queries) GetUserByUname(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUname, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
