// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mark_deleted.sql

package queries

import (
	"context"
)

const deleted = `-- name: Deleted :exec
update files set deleted = 1 where id = ?
`

func (q *Queries) Deleted(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleted, id)
	return err
}
