// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

type File struct {
	ID        int64
	Name      string
	CreatedAt string
	UpdatedAt string
	UserID    int64
	Deleted   int64
}

type User struct {
	ID        int64
	Username  string
	Password  string
	CreatedAt string
	UpdatedAt string
}
