// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: remove_user.sql

package queries

import (
	"context"
)

const removeUser = `-- name: RemoveUser :one
delete from users where id = ?

returning id, username, password, created_at, updated_at
`

func (q *Queries) RemoveUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, removeUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
