// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rollback_deletion.sql

package queries

import (
	"context"
)

const rollbackDelete = `-- name: RollbackDelete :one
update files set deleted = 0 where id = ?

returning id, name, created_at, updated_at, user_id, deleted
`

func (q *Queries) RollbackDelete(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRowContext(ctx, rollbackDelete, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Deleted,
	)
	return i, err
}
