// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user.sql

package queries

import (
	"context"
)

const updateUser = `-- name: UpdateUser :one
update users set username = ?, password = ?, updated_at = ? where id = ?

returning id, username, password, created_at, updated_at
`

type UpdateUserParams struct {
	Username  string
	Password  string
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.Password,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
