// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_file.sql

package queries

import (
	"context"
)

const updateFile = `-- name: UpdateFile :exec
update files set updated_at = ? where id = ?
`

type UpdateFileParams struct {
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) error {
	_, err := q.db.ExecContext(ctx, updateFile, arg.UpdatedAt, arg.ID)
	return err
}
